/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

let awsconfig = {
    aws_appsync_region: 'us-east-1',
    aws_appsync_authenticationType: 'API_KEY',
    aws_project_region: 'us-east-1',
    aws_appsync_graphqlEndpoint: 'https://ny5ncwhatvct5dxietxnh6fi2a.appsync-api.us-east-1.amazonaws.com/graphql',
    aws_appsync_apiKey: 'da2-aivxgwujk5hvdodjhwmkxq34lq' };

export default awsconfig;
